name: Lotofacil Auto Predict

on:
  push:
    paths:
      - 'Oraculo/Lotofacil/data/Lotofacil.csv'
  schedule:
    - cron: '0 12 * * *' # Executa diariamente às 9h BRT (12h UTC)
  workflow_dispatch:

jobs:
  predict-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install pandas numpy seaborn matplotlib tabulate plotly markdown2 jinja2 scipy

      - name: Executar pipeline completa
        run: |
          python Oraculo/Lotofacil/scripts/predict.py

      - name: Gerar HTML unificado
        run: |
          python scripts/generate_html.py

      - name: Executar benchmark
        run: |
          python Oraculo/Lotofacil/scripts/benchmark.py

      - name: Commit e push dos resultados
        run: |
          git config user.name "mzfshark"
          git config user.email "mzfshark@gmail.com"
          git pull
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Atualiza previsões e relatório da Lotofácil"
            git push
          else
            echo "Nenhuma mudança para comitar."
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Publicar via GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./
          publish_branch: gh-pages
          enable_jekyll: true
